/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_serialassistant_SerialPort */

#ifndef _Included_com_serialassistant_SerialPort
#define _Included_com_serialassistant_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_serialassistant_SerialPort
 * Method:    open
 * Signature: (I)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_serialassistant_SerialPort_open
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_serialassistant_SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_serialassistant_SerialPort_close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
